version: "3.7"

services:
  mysql:
    image: mysql:8.3.0-oracle
    container_name: blogapp-mysql
    ports:
      - "3306:3306"
    networks:
      - blogapp-network
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
      MYSQL_DATABASE: blogdb
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blogapp-phpmyadmin
    ports:
      - "8004:80"
    networks:
      - blogapp-network
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

volumes:
  mysql-database-data-volume:

networks:
  blogapp-network:

